# ######################################################################## #
# File:     /core/test/unit/CMakeLists.txt
#
# Purpose:  CMake lists for libver core unit tests
#
# ######################################################################## #

add_subdirectory(test.unit.libver.find)
add_subdirectory(test.unit.libver.python)
add_subdirectory(test.unit.libver.semver)


# ############################## end of file ############################# #
