# ######################################################################## #
# File:     /core/test/unit/CMakeLists.txt
#
# Purpose:  CMake lists for libver core unit tests
#
# ######################################################################## #

add_subdirectory(test.unit.libver.find)


# ############################## end of file ############################# #
