# ######################################################################## #
# File:     /core/test/component/CMakeLists.txt
#
# Purpose:  CMake lists for libver core component tests
#
# ######################################################################## #

add_subdirectory(test.component.libver.find)


# ############################## end of file ############################# #
