# ######################################################################## #
# File:     /core/test/scratch/CMakeLists.txt
#
# Purpose:  CMake lists for core scratch tests
#
# ######################################################################## #

add_subdirectory(libver)


# ############################## end of file ############################# #
