# ######################################################################## #
# File:     /core/test/scratch/zig/CMakeLists.txt
#
# Purpose:  CMake for the build.zig.zon scratch program
#
# ######################################################################## #

add_executable(test.scratch.zig
	entry.c
)

define_target_compile_options(test.scratch.zig)


# ############################## end of file ############################# #
